// Compiled by ClojureScript 0.0-2069
goog.provide('modern_cljs.model');
goog.require('cljs.core');
goog.require('shoreleave.remotes.http_rpc');
goog.require('cljs.core.async');
goog.require('shoreleave.remotes.http_rpc');
goog.require('cljs.core.async');
modern_cljs.model.appid = serverdata.gbcid;
modern_cljs.model.gameid = serverdata.gameid;
modern_cljs.model.gamename = serverdata.gamename;
modern_cljs.model.fqlquerygen = (function fqlquerygen(gameid){return [cljs.core.str("SELECT actor_id,app_id,post_id,attachment FROM stream WHERE filter_key IN (\"app_"),cljs.core.str(gameid),cljs.core.str("\")\n        AND actor_id!=me() AND created_time>"),cljs.core.str((moment().unix() - 86400)),cljs.core.str(" LIMIT 300")].join('');
});
modern_cljs.model.bonusquery = (function bonusquery(c){return FB.api((function (){var obj12829 = {"method":"fql.query","query":modern_cljs.model.fqlquerygen.call(null,modern_cljs.model.gameid)};return obj12829;
})(),(function (p1__12825_SHARP_){return cljs.core.async.put_BANG_.call(null,c,p1__12825_SHARP_);
}));
});
modern_cljs.model.getLatestLinks = (function getLatestLinks(sideeffect){return shoreleave.remotes.http_rpc.remote_callback.call(null,new cljs.core.Keyword(null,"latestLinks","latestLinks",1431724004),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [modern_cljs.model.gameid,100], null),sideeffect);
});
modern_cljs.model.insertBonuses = (function insertBonuses(bonuses){console.log(bonuses);
return shoreleave.remotes.http_rpc.remote_callback.call(null,new cljs.core.Keyword(null,"addBonuses","addBonuses",2986208414),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [bonuses], null),(function (p1__12830_SHARP_){return console.log([cljs.core.str("Result of insert bonuses: "),cljs.core.str(p1__12830_SHARP_)].join(''));
}));
});
modern_cljs.model.insertBonusesTest = (function insertBonusesTest(bonuses){console.log(bonuses);
return shoreleave.remotes.http_rpc.remote_callback.call(null,new cljs.core.Keyword(null,"addBonusesTest","addBonusesTest",4067241808),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [bonuses], null),(function (p1__12831_SHARP_){return console.log([cljs.core.str("Result of insert bonuses: "),cljs.core.str(p1__12831_SHARP_)].join(''));
}));
});
modern_cljs.model.insertTest = (function insertTest(){return shoreleave.remotes.http_rpc.remote_callback.call(null,new cljs.core.Keyword(null,"insertTest","insertTest",1980066397),cljs.core.PersistentVector.EMPTY,(function (p1__12832_SHARP_){return console.log("Result of the test is: ",cljs.core.nth.call(null,p1__12832_SHARP_,0));
}));
});
modern_cljs.model.streamSearch = (function streamSearch(searchTerm){console.log(searchTerm);
var query = [cljs.core.str("SELECT post_id, viewer_id, app_id, source_id, updated_time, created_time, filter_key, \n       attribution, actor_id, target_id, message, app_data, action_links, attachment, impressions, \n       comments, likes, privacy, permalink, xid, tagged_ids, message_tags, description, description_tags \n       FROM stream WHERE source_id = me() AND strpos(lower(message),'"),cljs.core.str(searchTerm),cljs.core.str("') >= 0 LIMIT 1000")].join('');return FB.api((function (){var obj12837 = {"method":"fql.query","query":query};return obj12837;
})(),(function (p1__12833_SHARP_){return console.log(p1__12833_SHARP_);
}));
});
